import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#0b0f10',
        'surface-container-low':    '#191c1e',
        'surface-container':        '#1d2022',
        'surface-container-high':   '#272a2c',
        'surface-container-highest':'#323537',
        'surface-bright':           '#363a3b',
        'surface-dim':              '#101415',
        'surface':                  '#101415',
        'surface-variant':          '#323537',
        'surface-tint':             '#c6c6c6',
        'background':               '#101415',
        'on-background':            '#e0e3e5',
        'on-surface':                 '#e0e3e5',
        'on-surface-variant':         '#cfc4c5',
        'primary':                    '#c6c6c6',
        'on-primary':                 '#303030',
        'primary-container':          '#000000',
        'on-primary-container':       '#757575',
        'primary-fixed':              '#e2e2e2',
        'primary-fixed-dim':          '#c6c6c6',
        'on-primary-fixed':           '#1b1b1b',
        'on-primary-fixed-variant':   '#474747',
        'inverse-primary':            '#5e5e5e',
        'secondary':                  '#ddb7ff',
        'on-secondary':               '#490080',
        'secondary-container':        '#6f00be',
        'on-secondary-container':     '#d6a9ff',
        'secondary-fixed':            '#f0dbff',
        'secondary-fixed-dim':        '#ddb7ff',
        'on-secondary-fixed':         '#2c0051',
        'on-secondary-fixed-variant': '#6900b3',
        'tertiary':                   '#4cd7f6',
        'on-tertiary':                '#003640',
        'tertiary-container':         '#000000',
        'on-tertiary-container':      '#008197',
        'tertiary-fixed':             '#acedff',
        'tertiary-fixed-dim':         '#4cd7f6',
        'on-tertiary-fixed':          '#001f26',
        'on-tertiary-fixed-variant':  '#004e5c',
        'error':                      '#ffb4ab',
        'on-error':                   '#690005',
        'error-container':            '#93000a',
        'on-error-container':         '#ffdad6',
        'outline':                    '#988e90',
        'outline-variant':            '#4c4546',
        'inverse-surface':            '#e0e3e5',
        'inverse-on-surface':         '#2d3133',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
      },
      spacing: {
        'margin-mobile':  '20px',
        'margin-desktop': '64px',
        'gutter-sm':      '16px',
        'gutter-md':      '24px',
        'unit':           '4px',
        'max-width':      '1440px',
      },
      fontFamily: {
        'display-xl':     ['var(--font-geist-sans)', 'Geist', 'sans-serif'],
        'display-lg':     ['var(--font-geist-sans)', 'Geist', 'sans-serif'],
        'display-mobile': ['var(--font-geist-sans)', 'Geist', 'sans-serif'],
        'headline-md':    ['var(--font-geist-sans)', 'Geist', 'sans-serif'],
        'body-md':        ['var(--font-geist-sans)', 'Geist', 'sans-serif'],
        'body-lg':        ['var(--font-geist-sans)', 'Geist', 'sans-serif'],
        'label-sm':       ['var(--font-geist-sans)', 'Geist', 'sans-serif'],
        'mono-code':      ['var(--font-geist-mono)', 'Geist Mono', 'monospace'],
      },
      fontSize: {
        'display-xl':     ['72px',  { lineHeight: '80px',  letterSpacing: '-0.04em', fontWeight: '800' }],
        'display-lg':     ['48px',  { lineHeight: '56px',  letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-mobile': ['36px',  { lineHeight: '44px',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md':    ['24px',  { lineHeight: '32px',  letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg':        ['18px',  { lineHeight: '28px',  letterSpacing: '0em',     fontWeight: '400' }],
        'body-md':        ['16px',  { lineHeight: '24px',  letterSpacing: '0em',     fontWeight: '400' }],
        'label-sm':       ['13px',  { lineHeight: '16px',  letterSpacing: '0.05em',  fontWeight: '500' }],
        'mono-code':      ['14px',  { lineHeight: '20px',  fontWeight: '400' }],
      },
      animation: {
        'shimmer': 'shimmer 2s infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
      },
    },
  },
  plugins: [],
}
export default config